// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  angular.module('myApp').controller('UsersCtrl', [
    '$scope', function($scope) {
      $scope.showAlert = function() {
        return alert('You clicked');
      };
      console.log('UsersCtrl');
      $scope.user_name = null;
      $scope.load_data = function() {
        return $scope.technologies = ['HTML', 'HTML5', 'Javascript', 'jQuery', 'Angular', 'C#', 'PHP', 'Ruby', 'Mongo', 'Expression', 'Node', 'Java', 'Ruby on Rails', 'Sinatra', 'Cuba', 'Padrino', 'Lotus', 'CodeIgniter', 'Laravel', 'Symfony', 'Cake'];
      };
    }
  ]);

}).call(this);
