// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('myApp', ['ngRoute', 'ngAnimate']).config([
    '$routeProvider', function($routeProvider) {
      $routeProvider.when('/users', {
        templateUrl: 'templates/users.html',
        controller: 'UsersCtrl'
      }).otherwise({
        redirectTo: '/users'
      });
    }
  ]);

}).call(this);
